version: '3.8'

services:
  python-lab:
    image: python:3.11-slim
    container_name: eng-lab-python
    command: tail -f /dev/null
    working_dir: /app
    volumes:
      - ./:/app

  node-lab:
    image: node:20-alpine
    container_name: eng-lab-node
    command: tail -f /dev/null
    working_dir: /app
    volumes:
      - ./:/app